### PR TITLE
fix #231: get --append working with --compress

### LINKED ISSUE #231: --append doesn't work with --compress
Here's the reproducer:

```
#!/bin/sh
set -eu
mkdir -vp archive-dir-create
mkdir -vp archive-dir-append
touch archive-dir-create/fee
touch archive-dir-create/fie
touch archive-dir-append/foe
touch archive-dir-append/fum

./makeself.sh --compress archive-dir-create archive.run "archive" echo "Hello, archive!"
./archive.run --info
./archive.run --list
./archive.run --check
./archive.run

./makeself.sh --compress --append archive-dir-append archive.run
./archive.run --info
./archive.run --list
./archive.run --check
./archive.run
```

Here's what the combined error and output looks like:
```
Header is 680 lines long

WARNING: Overwriting existing file: archive.run
About to compress 4 KB of data...
Adding files to archive named "archive.run"...
./fee
./fie
CRC: 3015349349
MD5: 7edd7a7f53d790d79c94a93986052c4f

Self-extractable archive "archive.run" successfully created.
Identification: archive
Target directory: archive-dir-create
Uncompressed size: 12 KB
Compression: Unix
Encryption: n
Date of packaging: Wed Nov 25 22:31:19 UTC 2020
Built with Makeself version 2.4.2 on
Build command was: ./makeself.sh \
    "--compress" \
    "archive-dir-create" \
    "archive.run" \
    "archive" \
    "echo" \
    "Hello, archive!"
Script run after extraction:
     echo Hello, archive!
archive-dir-create will be removed after extraction
Target directory: archive-dir-create
-rw-rw-r-- luser/luser         0 2020-11-25 22:31 ./fee
-rw-rw-r-- luser/luser         0 2020-11-25 22:31 ./fie
Verifying archive integrity... ./archive.run does not contain an embedded SHA256 checksum.
     0%  100%   MD5 checksums are OK. All good.
Verifying archive integrity...     0%  100%   MD5 checksums are OK. All good.
Uncompressing archive     0%  100%  
Hello, archive!
Header is 678 lines long

About to compress 4 KB of data...
Adding files to archive named "archive.run"...
./makeself.sh: 632: exec: 2>&-;: not found
./foe
./fum
CRC: 2863508341
MD5: fba999eedf906f8dc6cbca2c90c802ff
Self-extractable archive "archive.run" successfully updated.
Identification: archive
Target directory: archive-dir-create
Uncompressed size: 12 KB
Compression: Unix
Encryption: n
Date of packaging: Wed Nov 25 22:31:19 UTC 2020
Built with Makeself version 2.4.2 on
Build command was: ./makeself.sh \
    "--compress" \
    "--append" \
    "archive-dir-append" \
    "archive.run"
Script run after extraction:
     echo Hello, archive!
archive-dir-create will be removed after extraction
Target directory: archive-dir-create
-rw-rw-r-- luser/luser         0 2020-11-25 22:31 ./foe
-rw-rw-r-- luser/luser         0 2020-11-25 22:31 ./fum
Verifying archive integrity... ./archive.run does not contain an embedded SHA256 checksum.
     0%  100%   MD5 checksums are OK. All good.
Verifying archive integrity...     0%  100%   MD5 checksums are OK. All good.
Uncompressing archive     0%  100%  
Hello, archive!
```

You can see that the appended archive is missing the original members; i.e., it contains only those members added during the `--append` operation.

The problem is that the implicit extraction of the original archive fails because, during creation, the archive assigns `GUNZIP_CMD` as
```
GUNZIP_CMD="exec 2>&-; uncompress -c || test \\\$? -eq 2 || gzip -cd"
```

The during appending, this variable is expanded once and evaluated as a command. Since `exec: 2>&-;` is not a command, the decompression of the original compressed archive fails:
```
./makeself.sh: 632: exec: 2>&-;: not found
```

Rather than appending to the original decompressed archive, it appends to an empty file.

### PR DESCRIPTION
**Pull request by realtime-neil**
The decompression command specified by `--compress` does not match the
semantics required by the `--append` operation. Change the decompression
command for the `--compress` to match those of the other compression options.

edit `makeself.sh`:

* try to locate `gzip` and `compress` commands and set the `COMPRESS` variable
  appropriately. Change `COMPRESS` value for `compress` from `Unix` to
  `compress`.

* change switch block to match new value

* change `GUNZIP_CMD` from `exec` expression to `uncompress -cf`

edit `test/appendtest`:

* be clever with the way we setup the test archives

* test every compression option, if we have the required command

### CODE REVIEW

File: makeself.sh [hunk 1]
```diff
@@ -551,9 +554,9 @@ gpg-asymmetric)
     GUNZIP_CMD="gpg --yes -d"
     ENCRYPT="gpg"
     ;;
-Unix)
+compress)
     GZIP_CMD="compress -cf"
-    GUNZIP_CMD="exec 2>&-; uncompress -c || test \\\$? -eq 2 || gzip -cd"
+    GUNZIP_CMD="uncompress -cf"
```
Comment (megastep) [inline makeself.sh:559]: I think the reason we had it set up this way is because on some systems uncompress is not installed while gzip is, so we could still extract through it. Would there be a way to fix it without losing this?

File: makeself.sh [hunk 2]
```diff
@@ -173,10 +173,13 @@ MS_Usage()
 }
 
 # Default settings
-if type gzip > /dev/null 2>&1; then
+if command -v gzip >/dev/null 2>&1; then
```
Comment (megastep) [inline makeself.sh:176]: How portable is this `command` ?

File: makeself.sh (hunk 1 above)
Comment (realtime-neil) [reply makeself.sh:559]: I think I can make that work. I'll push when have something better.

File: makeself.sh (hunk 2 above)
Comment (realtime-neil) [reply makeself.sh:176]: Welp, the heirloom-sh http://heirloom.sourceforge.net/ doesn't have it, and that's reason enough for me to rip it out in favor of `which` and/or `type`. Fix forthcoming.

**Comment by realtime-neil** [comment]
@megastep , how does that look?

**Comment by megastep** [comment]
Better, thanks! I'll merge
